[build]
  command = "npm install && npm run build"
  publish = "project/.next"
  base = "project"

[build.environment]
  NODE_ENV = "production"
  # Optimisations de build sécurisé
  NEXT_TELEMETRY_DISABLED = "1"
  # Force la production même si Netlify ne l'a pas détecté
  CI = "true"

# Plugin Next.js pour Netlify (version mise à jour)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Protection contre l'accès aux fichiers sensibles
[[redirects]]
  from = "/.env*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/package*.json"
  to = "/404"
  status = 404

[[redirects]]
  from = "/.git/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/node_modules/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.log"
  to = "/404"
  status = 404

[[redirects]]
  from = "/wp-admin"
  to = "/404"
  status = 404

[[redirects]]
  from = "/phpMyAdmin"
  to = "/404"
  status = 404

[[redirects]]
  from = "/adminer*"
  to = "/404"
  status = 404

# Headers de sécurité renforcés
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(self)"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-ancestors 'none';"
    # Cache Control pour empêcher la mise en cache du code source
    Cache-Control = "no-cache, no-store, must-revalidate"

# Headers spéciaux pour les API (sécurité maximale)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Robots-Tag = "noindex, nofollow"

# Headers pour les pages admin (non-indexées et non-cachées)
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-store, no-cache, must-revalidate"

# Headers pour les pages de membres (non-indexées)
[[headers]]
  for = "/member/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Headers pour les pages de modérateurs (non-indexées)
[[headers]]
  for = "/moderator/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# Headers pour les assets statiques (cache optimisé)
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des fonctions (si nécessaire)
[functions]
  directory = "project/netlify/functions" 